setupVersion: 2
modelRoles: 
  default: anthropic/claude-opus-5:high
theme: 
  light: light-eucalyptus
  dark: light-eucalyptus
display: 
  showTokenUsage: true
personality: pragmatic
tools: 
  approvalMode: yolo
stt: 
  enabled: true
astGrep: 
  enabled: true
plan: 
  defaultOnStartup: true
todo: 
  reminders: false
hideThinkingBlock: false
dev: 
  autoqa: false
secrets: 
  enabled: true
composer: 
  shape: box