[[steamApps.windows.work]]
id = "1369320"
name = "Virtual Cottage"
folderName = "Virtual Cottage"

[[steamApps.windows.work]]
id = "2113850"
name = "Spirit City - Lofi Sessions"
folderName = "Spirit City Lofi Sessions"

[[steamApps.windows.work]]
id = "2826180"
name = "ChillPulse"
folderName = "ChillPulse"

[[steamApps.windows.work]]
id = "431960"
name = "Wallpaper Engine"
folderName = "wallpaper_engine"
