[[steamApps.windows.core]]
id = "1369320"
name = "Virtual Cottage"

[[steamApps.windows.core]]
id = "2113850"
name = "Spirit City - Lofi Sessions"

[[steamApps.windows.core]]
id = "2826180"
name = "Chillpulse"

[[steamApps.windows.core]]
id = "431960"
name = "Wallpaper Engine"
